version: "3"

services:

  backend-app:
    build: ./back-end
    user: node
    container_name: backend_api
    tty: true
    stdin_open: true
    command: dev
    image: backend-api:8.3
    restart: always
    working_dir: /app-backend
    volumes:
      - ./back-end/src:/app-backend/src
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: backend_api
      DB_PORT: 3306
      JWT_SECRET: secret

  db:
    container_name: backend_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password